---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: meta-app_wordpress
  remote_user: centos
  become: yes

  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress
    - heat
