---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: all
  remote_user: centos
  become_user: root
  # sudo: yes

  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress
    - heat
