---
- block:
    - name: Signal Heat about playbook completition
      uri:
        url: "{{heat_endpoint}}"
        method: POST
        headers:
          X-Auth-Token: "{{heat_token}}"
          Content-Type: "application/json"
          Accept: "application/json"
        body: '{"status": "SUCCESS"}'
        body_format: json
        force_basic_auth: yes
        status_code: 200
  rescue:
    - name: Signal Heat about playbook failure
      uri:
        url: "{{heat_endpoint}}"
        method: POST
        headers:
          X-Auth-Token: "{{heat_token}}"
          Content-Type: "application/json"
          Accept: "application/json"
        body: '{"status": "FAILURE"}'
        body_format: json
        force_basic_auth: yes
        status_code: 200
